<?php
// Test Motor Charging Report Generation
session_start();
$_SESSION['user_id'] = 3;
$_SESSION['username'] = 'admin';

require_once 'includes/db_connect.php';
require_once 'includes/report_functions.php';

echo "=== Testing Motor Charging Report Generation ===\n\n";

$rocket_id = 2;
echo "1. Testing canGenerateMotorChargingReport($rocket_id)...\n";
$can_generate = canGenerateMotorChargingReport($rocket_id, $pdo);
echo "Result: " . ($can_generate ? "TRUE (can generate)" : "FALSE (cannot generate)") . "\n\n";

if ($can_generate) {
    echo "2. Testing getMotorChargingReportData($rocket_id)...\n";
    $report_data = getMotorChargingReportData($rocket_id, $pdo);
    
    if ($report_data) {
        echo "✅ Report data generated successfully!\n";
        echo "- Rocket: {$report_data['rocket_info']['serial_number']}\n";
        echo "- Total steps: {$report_data['report_metadata']['total_steps']}\n";
        echo "- Approved steps: {$report_data['report_metadata']['approved_steps']}\n";
        echo "- Generated by: {$report_data['generated_by']}\n";
        echo "- Generated at: {$report_data['generated_at']}\n\n";
        
        echo "3. Testing controller access...\n";
        // Simulate controller call
        $_GET['rocket_id'] = $rocket_id;
        
        echo "✅ Ready to generate full HTML report!\n";
        echo "🚀 URL to test: controllers/motor_charging_report_controller.php?rocket_id=$rocket_id\n";
        
    } else {
        echo "❌ Failed to generate report data\n";
    }
} else {
    echo "❌ Cannot generate report - business rules not met\n";
}

echo "\n=== Test Complete ===\n";
?>
